### ISSUE TITLE
GPT Timeouts

### ISSUE THREAD

**Issue by wmdhosting** [digitalpulsebe/craft-multi-translator#10]
I just started to use translation with GPT 4 >> i have paid account. 

**WHen translating  single entry with sidebar iz works but  i get often..**  
cURL error 28: Operation timed out after 30001 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://api.openai.com/v1/chat/completions   

**When i try multiple entry .. everytime is failed..** 
cURL error 28: Operation timed out after 30001 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://api.openai.com/v1/chat/completions

I then tested same API key with  Content buddy plugin.. and dont get timouts.. 

Any idea..

**Comment by wmdhosting** [comment]
Tryed with google API..   too>> work ok for single entry..

Multiple entries..   goes to queue . but noting translated.. and no error in queve.. 

DeepL didnt tested as not supoorting source lang..

**Comment by JodebaDigitalPulse** [comment]
Hi, can you provide some context please?
What are the source and destination language? How large is the content, and what types of fields are they in?

You can enable some logging, add a file `config/multi-translator.php`
```
<?php

return [
    "debug" => true,
];
```
Maybe it will provide a clue.

In my tests the Chat-GPT api is always the slowest to respond, but 30s is really long.

**Comment by JodebaDigitalPulse** [comment]
Hi @wmdhosting, I'll test with your data as soon as possible. But you can already delete the log file, as it contains the keys. (Best way is to use environment variables for this, by the way)

Not everything from the SEOmatic is processed in the translation, but a lot of data is just dumped by $entry->getSerializedFieldValues(), so don't worry about that.

It seems you have a lot of fields marked as translatable. Relation fields do not always need to be translatable when the related Entries are translated on their own. Just a tip, because this should not affect the translation either.

Looks like there is a lot of inline styles in the HTML field, so I'll test if that is an issue. The plugin can not process the html, so it is up to the service (ChatGPT) to process the html correctly, but I guess they'll have their limits as well.

**Comment by JodebaDigitalPulse** [comment]
Hi, 

I might have a clue why translating in bulk (multiple by queue) does not work. You said you wanted to translate from Croatian to English. But in the logs I see you are translating from English (with Croatian content) to Croatian. 

So beware: when translating in bulk, you should be on the source language and select the target in the dropdown.
(when translating one by one, it is the other way around: you select the source on the target site)

I tested with your content, to use the Chat-GPT service, I took a long time, but never 30s. Are you ok for using the Google service, or should I go deeper in to this?

**Comment by wmdhosting** [comment]
Ok will use  Google. 

Yes. this translate  buttons get me little confused..     :)

I did allready have content  on english site..  but  was croatian content.. waiting to be translated

So seems i tryed all inverse.. :)

**Comment by JodebaDigitalPulse** [comment]
Hi, @wmdhosting, so everything is working? 🙂

**Comment by wmdhosting** [comment]
I started to think inverse..:)  so all works ok :)

With Google.
