### ISSUE TITLE
Overwrites all existing NEO blocks when translating

### ISSUE THREAD

**Issue by lenvanessen** [digitalpulsebe/craft-multi-translator#16]
If you share blocks between all sites, but only translate the fields within, this plug-in will break your site. It's not passing the original block ids to the field, so NEO will treat each translated block as a new block, removing alle existing blocks from all other pages an thus resulting in your latest translation being applied to all sites.

**Comment by bartdigitalpulse** [comment]
Hi @lenvanessen. Thanks for reporting this issue. We'll look at it as soon as possible.

**Comment by lenvanessen** [comment]
@bartdigitalpulse I opened a PR, after some debugging and testing this works well for our case here, we haven't tested matrix or other propagation methods, but it should work just fine.

There seem to have been some changes when craft optimized the saving of complex elements by tracking the delta's

**Comment by JodebaDigitalPulse** [comment]
Hi @lenvanessen,

indeed, it looks like something has been changed when upgrading Neo. 
But have you tried setting the propagation method of the Neo field to 'Save blocks to other sites with the same language'? Because this allows for each language/site version to have their own blocks.

If this helps, the PR won't be necessary. Your PR changes the behaviour of the other matrix types as well.

Let me know!
Best regards,

**Comment by lenvanessen** [comment]
@JodebaDigitalPulse we don't want that propagation method for our site, as our blocks need to be propagated to all sites, regardless of language.

**Comment by JodebaDigitalPulse** [comment]
Hi @lenvanessen , you're right: this should have the same behaviour as editing the Entry in the CMS. Can you try updating to 2.7.0? I had to alter your suggested code a little bit, but thank you for suggestion! 🙂
